group: travis_latest
language: python
cache: pip

python:
  - 3.6
  # - 3.7
matrix:
  include:
    - python: 3.6

stages:
  - Codestyle

jobs:
  include:
    - stage: Codestyle
      install: pip install flake8 yapf
      script:
        # stop the build if there are any unexpected flake8 issues
        - flake8 . --count --ignore=E126,E226,E704,E731,W503,W504 --max-complexity=16
          --show-source --statistics
        # exit-zero treats all errors as warnings.
        - flake8 . --count --exit-zero --max-complexity=10 --statistics
