data_params:
  num_workers: 4
  batch_size: 256
  in_csv: null
  tag2class: null
  in_csv_infer: "@TODO:change_me"
  datapath: "@TODO:change_me"

stages: null
callbacks_params:
  loader:
    callback: CheckpointCallback
  infer:
    callback: InferCallback
